# Generated by Django 4.1 on 2023-08-05 11:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_poll_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='unique_id',
            field=models.CharField(default=uuid.UUID('3ed503cd-7cf2-4b9b-b8ae-0ad2c2f30725'), max_length=100),
        ),
    ]
