# Generated by Django 4.1 on 2023-08-05 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_alter_poll_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='unique_id',
            field=models.CharField(max_length=100),
        ),
    ]
