# Generated by Django 4.1 on 2023-08-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_poll_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
