# Generated by Django 4.1 on 2023-08-13 02:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vote', '0011_alter_specialpoll_voters'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPollVoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField(default=datetime.datetime(2023, 8, 13, 3, 10, 2, 211071))),
                ('allowed', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('special_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.specialpoll')),
            ],
        ),
    ]
