# Generated by Django 4.1 on 2023-08-13 03:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0012_specialpollvoters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpollvoters',
            name='time_requested',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 4, 25, 40, 68112)),
        ),
        migrations.CreateModel(
            name='SpecialPollContestants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.specialpoll')),
            ],
        ),
    ]
