# Generated by Django 4.1 on 2023-08-14 11:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('title', models.CharField(default='', max_length=100)),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('description', models.TextField()),
                ('voters', models.PositiveIntegerField(default=0)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPollVoters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_requested', models.DateTimeField(default=datetime.datetime(2023, 8, 14, 12, 14, 42, 502675))),
                ('allowed', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('special_poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpecialPoll.specialpoll')),
            ],
        ),
        migrations.CreateModel(
            name='SpecialPollContestants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('votes', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SpecialPoll.specialpoll')),
            ],
        ),
    ]
