# Generated by Django 4.1 on 2023-08-15 15:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialPoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpollvoters',
            name='time_requested',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 1, 57, 133928)),
        ),
    ]
