# Generated by Django 4.1 on 2023-08-15 15:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialPoll', '0003_alter_specialpollvoters_time_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialpollvoters',
            name='time_requested',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 15, 16, 28, 41, 140708)),
        ),
    ]
