# Generated by Django 4.1 on 2023-08-17 07:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SpecialPoll', '0006_alter_specialpollvoters_time_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialpollcontestants',
            name='option_image',
            field=models.ImageField(default='', upload_to='special/option'),
        ),
        migrations.AlterField(
            model_name='specialpollvoters',
            name='time_requested',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 17, 8, 18, 28, 450185)),
        ),
    ]
