# Generated by Django 4.1 on 2023-08-15 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CashPoll', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CashPollVoter',
        ),
    ]
