# Generated by Django 4.1 on 2023-08-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_image',
            field=models.ImageField(default='', upload_to='option'),
        ),
    ]
